vim.pack.add({ "https://github.com/nvim-treesitter/nvim-treesitter" })

require("plugins.tree-sitter-custom")

require("nvim-treesitter").install({
    "bash",
    "c",
    "cpp",
    "c_sharp",
    "css",
    "glsl",
    "html",
    "javascript",
    "json",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "nix",
    "nu",
    "python",
    "rust",
    "slang",
    "supermd",
    "supermd_inline",
    "superhtml",
    "svelte",
    "tsx",
    "typescript",
    "typst",
    "yaml",
    "zig",
    "rocq",
    "ziggy",
    "ziggy_schema",
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {
        "bash",
        "c",
        "cpp",
        "cs",
        "css",
        "glsl",
        "help",
        "html",
        "javascript",
        "json",
        "latex",
        "lua",
        "markdown",
        "nix",
        "nu",
        "python",
        "rust",
        "slang",
	"supermd",
        "superhtml",
        "svelte",
        "tsx",
        "typescript",
        "typst",
        "vim",
        "yaml",
        "zig",
        "ziggy",
        "ziggy_schema",
        "coq",
    },
    callback = function()
        pcall(vim.treesitter.start)
    end,
})
