# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	{ on = "!",	run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
	{ on = "<C-n>", run = "plugin dragon", desc = "Drag file(s) with dragon" },
	{ on = "=", run = "plugin what-size", desc = "Calc size of selection or cwd" },

	{ on = [ "c", "a", "a" ], run = "plugin compress", desc = "Archive selected files" },
	{ on = [ "c", "a", "p" ], run = "plugin compress -p", desc = "Archive selected files (password)" },

	{ on = "<Enter>",   run = "plugin smart-enter", desc = "Enter selected directory" },

	# Don't wrap cursor
	{ on = "<Up>",   run = "arrow -1", desc = "Previous file" },
	{ on = "<Down>", run = "arrow 1", desc = "Next file" },
]
