require("core.options")
require("core.keymaps")

require("plugins.lsp-config")
require("plugins.autocompletion")
require("plugins.treesitter")
require("plugins.formatter")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.themery")
require("plugins.yazi")

require("plugins.misc.which-key")
require("plugins.misc.indent-blankline")
require("plugins.misc.autopairs")
require("plugins.misc.hlsearch")
require("plugins.misc.todo-comments")
require("plugins.misc.colorizer")
